version: '3.8'
services:
  existdb:
    image: existdb/existdb:latest
    ports:
      - "8080:8080"
    volumes:
      - existdb-data:/existdb/data
    environment:
      - EXIST_DB_ADMIN_PASSWORD=admin

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - existdb

volumes:
  existdb-data:
